---
plugin: amazon.aws.aws_ec2
aws_access_key_id: "{{ lookup('file', 'group_vars/vault-inventory.yml') | from_yaml | json_query('aws_access_key_id') }}"
aws_secret_key: "{{ lookup('file', 'group_vars/vault-inventory.yml') | from_yaml | json_query('aws_secret_key') }}"

include_filters:
- tag:Group:
  - bastion_nodes
  - application_nodes
keyed_groups:
  - prefix: reversinglabs_devops_task
    key: tags.Group
hostnames:
  - 'tag:Name'
compose:
  ansible_host: public_dns_name
